"""Constants for Activity Tracker."""

from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "activity_tracker"
INTEGRATION_NAME = "Activity Tracker"
INTEGRATION_VERSION = "2026.9.1"
PLATFORMS = (Platform.BINARY_SENSOR, Platform.SENSOR)

CONF_RULE = "rule"
CONF_TEMPLATE = "template"
CONF_NAME = "name"
CONF_PERIOD_METRICS = "period_metrics"
CONF_ENABLED_METRICS = "enabled_metrics"

PERIOD_TODAY = "current_day"
PERIOD_WEEK = "current_week"
PERIOD_MONTH = "current_month"
PERIODS = (PERIOD_TODAY, PERIOD_WEEK, PERIOD_MONTH)
PERIOD_PREVIOUS_DAY_PREFIX = "previous_day:"

METRIC_TOTAL_DURATION = "total_duration"
METRIC_SESSION_COUNT = "session_count"
METRIC_CURRENT_SESSION_DURATION = "current_session_duration"
METRIC_LAST_SESSION_DURATION = "last_session_duration"
METRIC_LAST_SESSION_START = "last_session_start"
METRIC_LAST_SESSION_END = "last_session_end"
METRIC_TIME_SINCE_LAST_SESSION = "time_since_last_session"
METRIC_AVERAGE_START_TIME = "average_start_time"
METRIC_AVERAGE_END_TIME = "average_end_time"
METRIC_AVERAGE_DAILY_DURATION = "average_daily_duration"
METRIC_AVERAGE_SESSION_DURATION = "average_session_duration"
METRIC_LONGEST_SESSION_DURATION = "longest_session_duration"
METRIC_SHORTEST_SESSION_DURATION = "shortest_session_duration"
METRIC_WEEKDAY_MAX = "weekday_highest_total"
METRICS = (
    METRIC_TOTAL_DURATION,
    METRIC_SESSION_COUNT,
    METRIC_CURRENT_SESSION_DURATION,
    METRIC_LAST_SESSION_DURATION,
    METRIC_LAST_SESSION_START,
    METRIC_LAST_SESSION_END,
    METRIC_TIME_SINCE_LAST_SESSION,
    METRIC_AVERAGE_START_TIME,
    METRIC_AVERAGE_END_TIME,
    METRIC_AVERAGE_DAILY_DURATION,
    METRIC_AVERAGE_SESSION_DURATION,
    METRIC_LONGEST_SESSION_DURATION,
    METRIC_SHORTEST_SESSION_DURATION,
    METRIC_WEEKDAY_MAX,
)

PERIOD_METRICS = frozenset(
    {
        METRIC_TOTAL_DURATION,
        METRIC_SESSION_COUNT,
        METRIC_AVERAGE_DAILY_DURATION,
        METRIC_AVERAGE_SESSION_DURATION,
        METRIC_LONGEST_SESSION_DURATION,
        METRIC_SHORTEST_SESSION_DURATION,
        METRIC_AVERAGE_START_TIME,
        METRIC_AVERAGE_END_TIME,
    }
)
NON_PERIOD_METRICS = tuple(metric for metric in METRICS if metric not in PERIOD_METRICS)

OPT_RETENTION_DAYS = "retention_days"
OPT_MINIMUM_SESSION_SECONDS = "minimum_session_seconds"
OPT_DURATION_UNIT = "duration_unit"
OPT_CROSS_MIDNIGHT_POLICY = "cross_midnight_policy"

CROSS_MIDNIGHT_STARTED_DAY = "started_day"
CROSS_MIDNIGHT_ENDED_DAY = "ended_day"
CROSS_MIDNIGHT_SPLIT = "split_at_midnight"
CROSS_MIDNIGHT_POLICIES = (
    CROSS_MIDNIGHT_STARTED_DAY,
    CROSS_MIDNIGHT_ENDED_DAY,
    CROSS_MIDNIGHT_SPLIT,
)
DEFAULT_CROSS_MIDNIGHT_POLICY = CROSS_MIDNIGHT_SPLIT

DEFAULT_RETENTION_DAYS = 90
DEFAULT_MINIMUM_SESSION_SECONDS = 0
DEFAULT_DURATION_UNIT = "h"
DURATION_UNITS = ("s", "min", "h")


def update_signal(entry_id: str) -> str:
    """Return the runtime update signal for an entry."""
    return f"{DOMAIN}_{entry_id}_updated"
